<?php declare(strict_types=1);

namespace JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks;

use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWork;
use JsonLDForWP\Plugin\Classes\Entities\Things\Places\CivicStructure;
use JsonLDForWP\Plugin\Classes\Entities\Things\Organizations\LocalBusiness as LocalBusiness_647e163d33270;
use JsonLDForWP\Plugin\Classes\Entities\Things\Places\LocalBusiness as LocalBusiness_647e163d33274;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\DefinedTerms\CategoryCode;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\PhysicalActivityCategory;
use JsonLDForWP\Plugin\Classes\Entities\Thing;
use JsonLDForWP\Plugin\Classes\Entities\DataTypes\Date;
use JsonLDForWP\Plugin\Classes\Entities\DataTypes\DateTime;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\WebContent;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Dataset;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Observations\Things\Intangibles\StructuredValues\QuantitativeValues\Observation;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Services\GovernmentService;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Datasets\DataFeed;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\ItemList;
use JsonLDForWP\Plugin\Classes\Entities\Things\Person;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Ratings\AggregateRating;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\WebPage;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\DefinedTerm;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Audience;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObjects\AudioObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Clip;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MusicRecording;
use JsonLDForWP\Plugin\Classes\Entities\Things\Organization;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Comment;
use JsonLDForWP\Plugin\Classes\Entities\Things\Place;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Rating;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Comments\CorrectionComment;
use JsonLDForWP\Plugin\Classes\Entities\Things\Places\AdministrativeAreas\Country;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\AlignmentObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Grant;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Language;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\StructuredValues\InteractionCounter;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Claim;
use JsonLDForWP\Plugin\Classes\Entities\Things\Product;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\StructuredValues\QuantitativeValue;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Demand;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Offer;
use JsonLDForWP\Plugin\Classes\Entities\Things\Events\PublicationEvent;
use JsonLDForWP\Plugin\Classes\Entities\Things\Event;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Review;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\QualitativeValues\SizeSpecification;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObjects\ImageObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Quantities\Duration;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObjects\VideoObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObjects\TextObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\StructuredValues\PropertyValue;
use JsonLDForWP\Plugin\Classes\Entities\Things\Action;

/**
* @package JsonLDForWP
*/
class SpecialAnnouncement extends CreativeWork{
	protected CivicStructure|LocalBusiness_647e163d33270|LocalBusiness_647e163d33274|null $announcementLocation = null;
	protected CategoryCode|PhysicalActivityCategory|string|Thing|null $category = null;
	protected Date|DateTime|null $datePosted = null;
	protected string|WebContent|null $diseasePreventionInfo = null;
	protected Dataset|Observation|string|WebContent|null $diseaseSpreadStatistics = null;
	protected string|WebContent|null $gettingTestedInfo = null;
	protected GovernmentService|null $governmentBenefitsInfo = null;
	protected string|WebContent|null $newsUpdatesAndGuidelines = null;
	protected string|WebContent|null $publicTransportClosuresInfo = null;
	protected string|WebContent|null $quarantineGuidelines = null;
	protected string|WebContent|null $schoolClosuresInfo = null;
	protected string|WebContent|null $travelBans = null;
	protected DataFeed|string|null $webFeed = null;
	protected Thing|null $about = null;
	protected string|null $abstract = null;
	protected string|null $accessMode = null;
	protected ItemList|null $accessModeSufficient = null;
	protected string|null $accessibilityAPI = null;
	protected string|null $accessibilityControl = null;
	protected string|null $accessibilityFeature = null;
	protected string|null $accessibilityHazard = null;
	protected string|null $accessibilitySummary = null;
	protected Person|null $accountablePerson = null;
	protected CreativeWork|string|null $acquireLicensePage = null;
	protected AggregateRating|null $aggregateRating = null;
	protected string|null $alternativeHeadline = null;
	protected string|WebPage|null $archivedAt = null;
	protected DefinedTerm|string|null $assesses = null;
	protected MediaObject|null $associatedMedia = null;
	protected Audience|null $audience = null;
	protected AudioObject|Clip|MusicRecording|null $audio = null;
	protected Organization|Person|null $author = null;
	protected string|null $award = null;
	protected Person|null $character = null;
	protected CreativeWork|string|null $citation = null;
	protected Comment|null $comment = null;
	protected int|null $commentCount = null;
	protected string|null $conditionsOfAccess = null;
	protected Place|null $contentLocation = null;
	protected Rating|string|null $contentRating = null;
	protected DateTime|null $contentReferenceTime = null;
	protected Organization|Person|null $contributor = null;
	protected Organization|Person|null $copyrightHolder = null;
	protected string|null $copyrightNotice = null;
	protected float|null $copyrightYear = null;
	protected CorrectionComment|string|null $correction = null;
	protected Country|null $countryOfOrigin = null;
	protected DefinedTerm|string|null $creativeWorkStatus = null;
	protected Organization|Person|null $creator = null;
	protected string|null $creditText = null;
	protected Date|DateTime|null $dateCreated = null;
	protected Date|DateTime|null $dateModified = null;
	protected Date|DateTime|null $datePublished = null;
	protected string|null $discussionUrl = null;
	protected string|null $editEIDR = null;
	protected Person|null $editor = null;
	protected AlignmentObject|null $educationalAlignment = null;
	protected DefinedTerm|string|null $educationalLevel = null;
	protected DefinedTerm|string|null $educationalUse = null;
	protected MediaObject|null $encoding = null;
	protected string|null $encodingFormat = null;
	protected CreativeWork|null $exampleOfWork = null;
	protected Date|DateTime|null $expires = null;
	protected Organization|Person|null $funder = null;
	protected Grant|null $funding = null;
	protected string|null $genre = null;
	protected CreativeWork|null $hasPart = null;
	protected string|null $headline = null;
	protected Language|string|null $inLanguage = null;
	protected InteractionCounter|null $interactionStatistic = null;
	protected string|null $interactivityType = null;
	protected Claim|null $interpretedAsClaim = null;
	protected bool|null $isAccessibleForFree = null;
	protected CreativeWork|Product|string|null $isBasedOn = null;
	protected bool|null $isFamilyFriendly = null;
	protected CreativeWork|string|null $isPartOf = null;
	protected DefinedTerm|string|null $keywords = null;
	protected DefinedTerm|string|null $learningResourceType = null;
	protected CreativeWork|string|null $license = null;
	protected Place|null $locationCreated = null;
	protected Thing|null $mainEntity = null;
	protected Organization|Person|null $maintainer = null;
	protected Product|string|null $material = null;
	protected QuantitativeValue|string|null $materialExtent = null;
	protected Thing|null $mentions = null;
	protected Demand|Offer|null $offers = null;
	protected DefinedTerm|string|null $pattern = null;
	protected int|string|null $position = null;
	protected Organization|Person|null $producer = null;
	protected Organization|Person|null $provider = null;
	protected PublicationEvent|null $publication = null;
	protected Organization|Person|null $publisher = null;
	protected Organization|null $publisherImprint = null;
	protected CreativeWork|string|null $publishingPrinciples = null;
	protected Event|null $recordedAt = null;
	protected PublicationEvent|null $releasedEvent = null;
	protected Review|null $review = null;
	protected string|null $schemaVersion = null;
	protected Date|null $sdDatePublished = null;
	protected CreativeWork|string|null $sdLicense = null;
	protected Organization|Person|null $sdPublisher = null;
	protected DefinedTerm|QuantitativeValue|SizeSpecification|string|null $size = null;
	protected Organization|null $sourceOrganization = null;
	protected Place|null $spatial = null;
	protected Place|null $spatialCoverage = null;
	protected Organization|Person|null $sponsor = null;
	protected DefinedTerm|string|null $teaches = null;
	protected DateTime|string|null $temporal = null;
	protected DateTime|string|null $temporalCoverage = null;
	protected string|null $text = null;
	protected ImageObject|null $thumbnail = null;
	protected string|null $thumbnailUrl = null;
	protected Duration|null $timeRequired = null;
	protected CreativeWork|null $translationOfWork = null;
	protected Organization|Person|null $translator = null;
	protected string|null $typicalAgeRange = null;
	protected CreativeWork|string|null $usageInfo = null;
	protected float|string|null $version = null;
	protected Clip|VideoObject|null $video = null;
	protected CreativeWork|null $workExample = null;
	protected CreativeWork|null $workTranslation = null;
	protected string|null $additionalType = null;
	protected string|null $alternateName = null;
	protected string|TextObject|null $description = null;
	protected string|null $disambiguatingDescription = null;
	protected PropertyValue|string|null $identifier = null;
	protected ImageObject|string|null $image = null;
	protected CreativeWork|string|null $mainEntityOfPage = null;
	protected string|null $name = null;
	protected Action|null $potentialAction = null;
	protected string|null $sameAs = null;
	protected CreativeWork|Event|null $subjectOf = null;
	protected string|null $url = null;

	public function description():string {
		return __("A SpecialAnnouncement combines a simple date-stamped textual information update\n      with contextualized Web links and other structured data.  It represents an information update made by a\n      locally-oriented organization, for example schools, pharmacies, healthcare providers,  community groups, police,\n      local government.\n\nFor work in progress guidelines on Coronavirus-related markup see this doc.\n\nThe motivating scenario for SpecialAnnouncement is the Coronavirus pandemic, and the initial vocabulary is oriented to this urgent situation. Schema.org\nexpect to improve the markup iteratively as it is deployed and as feedback emerges from use. In addition to our\nusual Github entry, feedback comments can also be provided in this document.\n\nWhile this schema is designed to communicate urgent crisis-related information, it is not the same as an emergency warning technology like CAP, although there may be overlaps. The intent is to cover\nthe kinds of everyday practical information being posted to existing websites during an emergency situation.\n\nSeveral kinds of information can be provided:\n\nWe encourage the provision of 'name', 'text', 'datePosted', 'expires' (if appropriate), 'category' and\n'url' as a simple baseline. It is important to provide a value for 'category' where possible, most ideally as a well known\nURL from Wikipedia or Wikidata. In the case of the 2019-2020 Coronavirus pandemic, this should be 'https://en.wikipedia.org/w/index.php?title=2019-20_coronavirus_pandemic' or 'https://www.wikidata.org/wiki/Q81068910'.\n\nFor many of the possible properties, values can either be simple links or an inline description, depending on whether a summary is available. For a link, provide just the URL of the appropriate page as the property's value. For an inline description, use a WebContent type, and provide the url as a property of that, alongside at least a simple 'text' summary of the page. It is\nunlikely that a single SpecialAnnouncement will need all of the possible properties simultaneously.\n\nWe expect that in many cases the page referenced might contain more specialized structured data, e.g. contact info, openingHours, Event, FAQPage etc. By linking to those pages from a SpecialAnnouncement you can help make it clearer that the events are related to the situation (e.g. Coronavirus) indicated by the category property of the SpecialAnnouncement.\n\nMany SpecialAnnouncements will relate to particular regions and to identifiable local organizations. Use spatialCoverage for the region, and announcementLocation to indicate specific LocalBusinesses and CivicStructures. If the announcement affects both a particular region and a specific location (for example, a library closure that serves an entire region), use both spatialCoverage and announcementLocation.\n\nThe about property can be used to indicate entities that are the focus of the announcement. We now recommend using about only\nfor representing non-location entities (e.g. a Course or a RadioStation). For places, use announcementLocation and spatialCoverage. Consumers of this markup should be aware that the initial design encouraged the use of about for locations too.\n\nThe basic content of SpecialAnnouncement is similar to that of an RSS or Atom feed. For publishers without such feeds, basic feed-like information can be shared by posting\nSpecialAnnouncement updates in a page, e.g. using JSON-LD. For sites with Atom/RSS functionality, you can point to a feed\nwith the webFeed property. This can be a simple URL, or an inline DataFeed object, with encodingFormat providing\nmedia type information, e.g. 'application/rss+xml' or 'application/atom+xml'.", 'jsonld-for-wordpress');
	}
}