<?php declare(strict_types=1);

namespace JsonLDForWP\Plugin\Classes\Entities\Things\Products;

use JsonLDForWP\Plugin\Classes\Entities\Things\Product;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalIntangibles\DrugStrength;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalIntangibles\DoseSchedule;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\DrugClass;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\HealthInsurancePlan;
use JsonLDForWP\Plugin\Classes\Entities\Things\Products\Drugs\Things\MedicalEntities\Substances\Drug as Drug_647e171c2ce2c;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalIntangibles\DrugLegalStatus;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\MedicalEnumeration;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalIntangibles\DoseSchedules\MaximumDoseSchedule;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\MedicalEnumerations\DrugPregnancyCategory;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\MedicalEnumerations\DrugPrescriptionStatus;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\StructuredValues\PropertyValue;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Ratings\AggregateRating;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Audience;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Brand;
use JsonLDForWP\Plugin\Classes\Entities\Things\Organization;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\DefinedTerms\CategoryCode;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\PhysicalActivityCategory;
use JsonLDForWP\Plugin\Classes\Entities\Thing;
use JsonLDForWP\Plugin\Classes\Entities\Things\Places\AdministrativeAreas\Country;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Quantities\Distance;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\StructuredValues\QuantitativeValue;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Grant;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\AdultOrientedEnumeration;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\EnergyConsumptionDetails;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\MerchantReturnPolicy;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Service;
use JsonLDForWP\Plugin\Classes\Entities\Things\Products\ProductGroup;
use JsonLDForWP\Plugin\Classes\Entities\Things\Products\ProductModel;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\OfferItemCondition;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\DefinedTerm;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObjects\ImageObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\ItemList;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\ListItem;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\WebContent;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Demand;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Offer;
use JsonLDForWP\Plugin\Classes\Entities\DataTypes\Date;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\Review;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\QualitativeValues\SizeSpecification;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\DefinedTerms\CategoryCodes\MedicalCodes\Things\MedicalEntities\MedicalIntangibles\MedicalCode as MedicalCode_647e171cda3ce;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\DefinedTerms\CategoryCodes\MedicalCode as MedicalCode_647e171cda3d1;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalIntangibles\MedicalCode as MedicalCode_647e171cda3d2;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalGuideline;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\MedicalEnumerations\MedicineSystem;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\MedicalEnumerations\MedicalSpecialties\Things\Intangibles\Enumerations\Specialties\MedicalSpecialty as MedicalSpecialty_647e171cda3e0;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\MedicalEnumerations\MedicalSpecialty as MedicalSpecialty_647e171cda3e1;
use JsonLDForWP\Plugin\Classes\Entities\Things\Intangibles\Enumerations\Specialties\MedicalSpecialty as MedicalSpecialty_647e171cda3e2;
use JsonLDForWP\Plugin\Classes\Entities\Things\MedicalEntities\MedicalStudy;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWorks\MediaObjects\TextObject;
use JsonLDForWP\Plugin\Classes\Entities\Things\CreativeWork;
use JsonLDForWP\Plugin\Classes\Entities\Things\Action;
use JsonLDForWP\Plugin\Classes\Entities\Things\Event;

/**
* @package JsonLDForWP
*/
class Drug extends Product{
	protected string|null $activeIngredient = null;
	protected string|null $administrationRoute = null;
	protected string|null $alcoholWarning = null;
	protected DrugStrength|null $availableStrength = null;
	protected string|null $breastfeedingWarning = null;
	protected string|null $clinicalPharmacology = null;
	protected string|null $dosageForm = null;
	protected DoseSchedule|null $doseSchedule = null;
	protected DrugClass|null $drugClass = null;
	protected string|null $drugUnit = null;
	protected string|null $foodWarning = null;
	protected HealthInsurancePlan|null $includedInHealthInsurancePlan = null;
	protected Drug_647e171c2ce2c|null $interactingDrug = null;
	protected bool|null $isAvailableGenerically = null;
	protected bool|null $isProprietary = null;
	protected string|null $labelDetails = null;
	protected DrugLegalStatus|MedicalEnumeration|string|null $legalStatus = null;
	protected MaximumDoseSchedule|null $maximumIntake = null;
	protected string|null $mechanismOfAction = null;
	protected string|null $nonProprietaryName = null;
	protected string|null $overdosage = null;
	protected DrugPregnancyCategory|null $pregnancyCategory = null;
	protected string|null $pregnancyWarning = null;
	protected string|null $prescribingInfo = null;
	protected DrugPrescriptionStatus|string|null $prescriptionStatus = null;
	protected string|null $proprietaryName = null;
	protected Drug_647e171c2ce2c|null $relatedDrug = null;
	protected string|null $rxcui = null;
	protected string|null $warning = null;
	protected PropertyValue|null $additionalProperty = null;
	protected AggregateRating|null $aggregateRating = null;
	protected string|null $asin = null;
	protected Audience|null $audience = null;
	protected string|null $award = null;
	protected Brand|Organization|null $brand = null;
	protected CategoryCode|PhysicalActivityCategory|string|Thing|null $category = null;
	protected string|null $color = null;
	protected string|null $countryOfAssembly = null;
	protected string|null $countryOfLastProcessing = null;
	protected Country|null $countryOfOrigin = null;
	protected Distance|QuantitativeValue|null $depth = null;
	protected Grant|null $funding = null;
	protected string|null $gtin = null;
	protected string|null $gtin12 = null;
	protected string|null $gtin13 = null;
	protected string|null $gtin14 = null;
	protected string|null $gtin8 = null;
	protected AdultOrientedEnumeration|null $hasAdultConsideration = null;
	protected EnergyConsumptionDetails|null $hasEnergyConsumptionDetails = null;
	protected QuantitativeValue|null $hasMeasurement = null;
	protected MerchantReturnPolicy|null $hasMerchantReturnPolicy = null;
	protected Distance|QuantitativeValue|null $height = null;
	protected string|null $inProductGroupWithID = null;
	protected Product|null $isAccessoryOrSparePartFor = null;
	protected Product|null $isConsumableFor = null;
	protected bool|null $isFamilyFriendly = null;
	protected Product|Service|null $isRelatedTo = null;
	protected Product|Service|null $isSimilarTo = null;
	protected ProductGroup|ProductModel|null $isVariantOf = null;
	protected OfferItemCondition|null $itemCondition = null;
	protected DefinedTerm|string|null $keywords = null;
	protected ImageObject|string|null $logo = null;
	protected Organization|null $manufacturer = null;
	protected Product|string|null $material = null;
	protected string|null $mobileUrl = null;
	protected ProductModel|string|null $model = null;
	protected string|null $mpn = null;
	protected ItemList|ListItem|string|WebContent|null $negativeNotes = null;
	protected string|null $nsn = null;
	protected Demand|Offer|null $offers = null;
	protected DefinedTerm|string|null $pattern = null;
	protected ItemList|ListItem|string|WebContent|null $positiveNotes = null;
	protected string|null $productID = null;
	protected Date|null $productionDate = null;
	protected Date|null $purchaseDate = null;
	protected Date|null $releaseDate = null;
	protected Review|null $review = null;
	protected DefinedTerm|QuantitativeValue|SizeSpecification|string|null $size = null;
	protected string|null $sku = null;
	protected string|null $slogan = null;
	protected QuantitativeValue|null $weight = null;
	protected Distance|QuantitativeValue|null $width = null;
	protected MedicalCode_647e171cda3ce|MedicalCode_647e171cda3d1|MedicalCode_647e171cda3d2|null $code = null;
	protected MedicalGuideline|null $guideline = null;
	protected MedicineSystem|null $medicineSystem = null;
	protected Organization|null $recognizingAuthority = null;
	protected MedicalSpecialty_647e171cda3e0|MedicalSpecialty_647e171cda3e1|MedicalSpecialty_647e171cda3e2|null $relevantSpecialty = null;
	protected MedicalStudy|null $study = null;
	protected string|null $additionalType = null;
	protected string|null $alternateName = null;
	protected string|TextObject|null $description = null;
	protected string|null $disambiguatingDescription = null;
	protected PropertyValue|string|null $identifier = null;
	protected ImageObject|string|null $image = null;
	protected CreativeWork|string|null $mainEntityOfPage = null;
	protected string|null $name = null;
	protected Action|null $potentialAction = null;
	protected string|null $sameAs = null;
	protected CreativeWork|Event|null $subjectOf = null;
	protected string|null $url = null;

	public function description():string {
		return __("A chemical or biologic substance, used as a medical therapy, that has a physiological effect on an organism. Here the term drug is used interchangeably with the term medicine although clinical knowledge makes a clear difference between them.", 'jsonld-for-wordpress');
	}
}